-- This script was generated by the Schema Diff utility in pgAdmin 4
-- For the circular dependencies, the order in which Schema Diff writes the objects is not very sophisticated
-- and may require manual changes to the script to ensure changes are applied in the correct order.
-- Please report an issue for any failure with the reproduction steps.

ALTER TABLE IF EXISTS public.counters
    ADD COLUMN target bigint NOT NULL DEFAULT '1'::bigint;

COMMENT ON COLUMN public.counters.target
    IS 'Target count value';

CREATE OR REPLACE VIEW public.view_counters
    AS
     SELECT c.id,
    c.created_at,
    c.updated_at,
    c.name,
    c.user_id,
    count(e.id) AS count,
    c.sort_index,
    c.target
   FROM counters c
     LEFT JOIN counter_events e ON e.counter_id = c.id
  GROUP BY c.id, c.name, c.created_at, c.updated_at, c.user_id, c.sort_index, c.target;
